/// A reason why the notification is closed.
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum CloseReason {
    /// Expired timeout. The notification was closed automatically upon expiration of the timeout.
    Expired,

    /// Dismissed by the user.
    ///
    /// Generated by a call to [`crate::NotificationService::dismiss_notification`]
    /// and [`crate::NotificationHandle::dismiss`]
    Dismissed,

    /// The application requested to close the notification.
    DBusCall,

    /// Undefined/reserved reasons.
    Other,
}

impl From<u32> for CloseReason {
    fn from(value: u32) -> Self {
        match value {
            1 => Self::Expired,
            2 => Self::Dismissed,
            3 => Self::DBusCall,
            _ => Self::Other,
        }
    }
}

impl From<CloseReason> for u32 {
    fn from(value: CloseReason) -> Self {
        match value {
            CloseReason::Expired => 1,
            CloseReason::Dismissed => 2,
            CloseReason::DBusCall => 3,
            CloseReason::Other => 4,
        }
    }
}
