[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
gtk4 = { version = "0.10.3", features = ["v4_18"] }
notification_service_gobject = { path = "../notification_service_gobject" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
