# SPDX-FileCopyrightText: 2026 linkfrg
# SPDX-License-Identifier: CC0-1.0

[library]
description = "The GLib/GObject bindings for Ignis Notifications"
authors = "linkfrg"
license = "MIT"
browse_url = "https://github.com/ignis-sh/ignis"
repository_url = "https://github.com/ignis-sh/ignis.git"
website_url = "https://ignis-sh.github.io/ignis"

dependencies = [
    "GObject-2.0",
    "GLib-2.0",
    "Gio-2.0",
    "GdkPixbuf-2.0",
]

[dependencies."GObject-2.0"]
name = "GObject"
description = "The base type system library"
docs_url = "https://docs.gtk.org/gobject"

[dependencies."Gio-2.0"]
name = "Gio"
description = "GObject Interfaces and Objects, Networking, IPC, and I/O"
docs_url = "https://docs.gtk.org/gio"

[dependencies."GLib-2.0"]
name = "GLib"
description = "GLib is a general-purpose, portable utility library, which provides many useful data types, macros, type conversions, string utilities, file utilities, a mainloop abstraction, and so on."
docs_url = "https://docs.gtk.org/glib"

[dependencies."GdkPixbuf-2.0"]
name = "GdkPixbuf"
description = "Image loading library"
docs_url = "https://docs.gtk.org/gdk-pixbuf"
