[package]
name = "notifications"
version = "0.1.0"
edition = "2024"

[dependencies]
glib.workspace = true
gio.workspace = true
tokio.workspace = true
gdk-pixbuf.workspace = true
tracing.workspace = true

serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.17"
zbus = "5.12.0"
zvariant = { version = "5.8.0", features = ["arrayvec"] }

[dev-dependencies]
fake = "5.1.0"
rand = "0.10.2"
notify-rust = "4"
tempfile = "3.27.0"
